/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Habit = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'emoji' : IDL.Text,
});
export const JournalEntry = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'priority' : IDL.Text,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'note' : IDL.Text,
  'createdAt' : IDL.Int,
  'type' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const HabitLog = IDL.Record({ 'date' : IDL.Text, 'habitId' : IDL.Nat });

export const idlService = IDL.Service({
  'addHabit' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'addJournalEntry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addTask' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addTransaction' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteHabit' : IDL.Func([IDL.Nat], [], []),
  'deleteJournalEntry' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
  'getAllHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
  'getAllJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getHabitLogs' : IDL.Func([IDL.Nat], [IDL.Vec(HabitLog)], ['query']),
  'logHabit' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'toggleTaskComplete' : IDL.Func([IDL.Nat], [], []),
  'updateHabit' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateJournalEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateTask' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateTransaction' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Habit = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'emoji' : IDL.Text,
  });
  const JournalEntry = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'priority' : IDL.Text,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'note' : IDL.Text,
    'createdAt' : IDL.Int,
    'type' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const HabitLog = IDL.Record({ 'date' : IDL.Text, 'habitId' : IDL.Nat });
  
  return IDL.Service({
    'addHabit' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'addJournalEntry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addTask' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addTransaction' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteHabit' : IDL.Func([IDL.Nat], [], []),
    'deleteJournalEntry' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
    'getAllHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
    'getAllJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getHabitLogs' : IDL.Func([IDL.Nat], [IDL.Vec(HabitLog)], ['query']),
    'logHabit' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'toggleTaskComplete' : IDL.Func([IDL.Nat], [], []),
    'updateHabit' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateJournalEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateTask' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateTransaction' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };