/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Habit { 'id' : bigint, 'name' : string, 'emoji' : string }
export interface HabitLog { 'date' : string, 'habitId' : bigint }
export interface JournalEntry {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'date' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
}
export interface Task {
  'id' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'completed' : boolean,
  'dueDate' : string,
  'description' : string,
  'category' : string,
  'priority' : string,
}
export interface Transaction {
  'id' : bigint,
  'date' : string,
  'note' : string,
  'createdAt' : bigint,
  'type' : string,
  'category' : string,
  'amount' : number,
}
export interface _SERVICE {
  'addHabit' : ActorMethod<[string, string], bigint>,
  'addJournalEntry' : ActorMethod<[string, string, string], bigint>,
  'addTask' : ActorMethod<[string, string, string, string, string], bigint>,
  'addTransaction' : ActorMethod<
    [string, string, number, string, string],
    bigint
  >,
  'deleteHabit' : ActorMethod<[bigint], undefined>,
  'deleteJournalEntry' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'deleteTransaction' : ActorMethod<[bigint], undefined>,
  'getAllHabits' : ActorMethod<[], Array<Habit>>,
  'getAllJournalEntries' : ActorMethod<[], Array<JournalEntry>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getHabitLogs' : ActorMethod<[bigint], Array<HabitLog>>,
  'logHabit' : ActorMethod<[bigint, string], undefined>,
  'toggleTaskComplete' : ActorMethod<[bigint], undefined>,
  'updateHabit' : ActorMethod<[bigint, string, string], undefined>,
  'updateJournalEntry' : ActorMethod<
    [bigint, string, string, string],
    undefined
  >,
  'updateTask' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
  'updateTransaction' : ActorMethod<
    [bigint, string, string, number, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];